version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - app-network
    secrets:
      - firebase_credentials
    environment:
      - FIREBASE_CREDENTIALS_PATH=/run/secrets/firebase_credentials

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

secrets:
  firebase_credentials:
    file: ./firebase_credentials.json